###############
# GG Teleport #
# By  GusGold #
###############
#   Config    #
###############

# NOTE:
#    - Delete this file to regenerate it with default values
#    - If values are not viable, default will be used

Version: 0.9.3
checkForUpdates: true

# Default radius used on /tpr command
xRadius: 250
zRadius: 250

# List of block's Data Values that you don't want to be teleported on to
# Official List can be found at http://www.minecraftwiki.net/wiki/Data_values
blockBlackList:
- 8
- 9
- 10
- 11

# To have a portal that activates /tpr, make a real portal in your world
# then put the coordinates of a box that contains the portal down below
# Make sure your world is spelled correctly. Leave world black to disable
portal:
  world: world
  pos1:
    X: -10
    Y: 63
    Z: -10
  pos2:
    X: 10
    Y: 66
    Z: 10

# Maximum tries per run to find a viable spawn location
# (Higher value = potentially more delay)
# Set to -1 for unlimited tries (Likely to enter near-infinite loop)
maximumTries: 100
