name: GGTeleport
main: com.au_craft.GGTeleport.GGTeleport
version: 0.1

commands:
  tpr:
    descrption: Base Teleportation command.
    usage: /tpr
    permission: GGTeleport.random
    permission-message: You do not have permission for that.
